# Generated by Django 3.2.6 on 2023-05-27 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(help_text='name', max_length=100, verbose_name='college name')),
                ('college_address', models.CharField(help_text='address', max_length=100, verbose_name='address')),
                ('college_estd', models.CharField(help_text='estd', max_length=100, verbose_name='estd')),
                ('college_state', models.CharField(help_text='state', max_length=100, verbose_name='state')),
                ('college_affliated_to', models.CharField(help_text='affliation', max_length=100, verbose_name='affliation')),
                ('college_type', models.CharField(help_text='type', max_length=100, verbose_name='type')),
                ('college_zipcode', models.CharField(help_text='zipcode', max_length=100, verbose_name='zipcode')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(help_text='course name', max_length=1000, verbose_name='course name')),
                ('course_code', models.CharField(help_text='course name', max_length=1000, verbose_name='course name')),
                ('course_intake', models.IntegerField(help_text='intake', verbose_name='student intake')),
                ('course_duration', models.FloatField(blank=True, default=0.0)),
                ('is_cgpa', models.BooleanField(default=False, help_text='is_cgpa', verbose_name='is cgpa')),
                ('cgpa_scale', models.IntegerField(help_text='cgpa scale', verbose_name='course cgpa scale')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.college')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_desc', models.CharField(help_text='document desc', max_length=100, verbose_name='document desc')),
                ('base_cost', models.FloatField(blank=True, default=0.0)),
                ('gst_percentage', models.FloatField(blank=True, default=0.0)),
                ('delivery_charges', models.FloatField(blank=True, default=0.0)),
                ('download_charges', models.FloatField(blank=True, default=0.0)),
                ('download_gst_charges', models.FloatField(blank=True, default=0.0)),
                ('is_courier_available', models.BooleanField(default=False, help_text='is_delivery_avail?', verbose_name='is courier avail')),
                ('extra_info', models.CharField(help_text='document info', max_length=5000, verbose_name='document extra info')),
                ('college_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.college')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(help_text='subject name', max_length=1000, verbose_name='subject name')),
                ('subject_code', models.CharField(help_text='subject desc', max_length=1000, verbose_name='subject desc')),
                ('subject_semester', models.IntegerField(help_text='sem taught in', verbose_name='subject sem')),
                ('subject_year', models.IntegerField(help_text='year taught in', verbose_name='subject year')),
                ('credits', models.FloatField(blank=True, default=0.0)),
                ('max_marks', models.FloatField(blank=True, default=0.0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.course')),
            ],
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_sl_no', models.CharField(help_text='serial no', max_length=1000, verbose_name='document serial no')),
                ('document_url', models.CharField(help_text='url', max_length=2000, verbose_name='document url')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.document')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_amount', models.FloatField(blank=True, default=0.0)),
                ('cgpa', models.FloatField(blank=True, default=0.0)),
                ('percentage', models.FloatField(blank=True, default=0.0)),
                ('division', models.IntegerField(help_text='division', verbose_name='student class division')),
                ('unique_id', models.CharField(help_text='unique id', max_length=1000, verbose_name='unique id')),
                ('fathers_name', models.CharField(help_text='fathers name', max_length=1000, verbose_name='name of father')),
                ('mothers_name', models.CharField(help_text='mothers name', max_length=1000, verbose_name='mothers name')),
                ('admitted_year', models.IntegerField(help_text='year admitted', verbose_name='year admitted')),
                ('total_tickets_opened', models.IntegerField(help_text='total_tickets', verbose_name='tickets raised total')),
                ('total_tickets_closed', models.IntegerField(help_text='total_tickets_closed', verbose_name='tickets closed total')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.college')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.FloatField(blank=True, default=0.0)),
                ('max_marks', models.FloatField(blank=True, default=0.0)),
                ('grade', models.CharField(help_text='subject grade', max_length=100, verbose_name='subject grade')),
                ('credits_awarded', models.FloatField(blank=True, default=0.0)),
                ('max_credits', models.FloatField(blank=True, default=0.0)),
                ('is_marks', models.BooleanField(default=False, help_text='ismarks', verbose_name='is marks')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.subject')),
            ],
        ),
    ]
