# Generated by Django 3.2.6 on 2023-05-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_studentdocument_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='has_passed',
            field=models.BooleanField(default=False, help_text='pass/fail', verbose_name='pass or fail'),
        ),
    ]
